using Microsoft.EntityFrameworkCore;

namespace RhythmFlow.Api.Data;

/// <summary>
/// Adds tables that were introduced after a database was first created. EnsureCreated only builds a brand-new database and
/// never changes an existing one, so without this a server that was deployed earlier would be missing the newer tables.
/// Every statement is "IF NOT EXISTS", so it is safe on every start and does nothing on a fresh database.
/// Use this for small additive changes until EF Core migrations are adopted.
/// </summary>
public static class SchemaUpgrades
{
    public static async Task ApplyAsync(AppDbContext db)
    {
        string[] statements;
        if (db.Database.IsNpgsql())
        {
            statements =
            [
                """
                CREATE TABLE IF NOT EXISTS "DeviceTokens" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" uuid NOT NULL,
                    "Token" character varying(512) NOT NULL,
                    "Platform" character varying(20) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "LastSeen" timestamp with time zone NOT NULL
                )
                """,
                """CREATE UNIQUE INDEX IF NOT EXISTS "IX_DeviceTokens_Token" ON "DeviceTokens" ("Token")""",
                """CREATE INDEX IF NOT EXISTS "IX_DeviceTokens_UserId" ON "DeviceTokens" ("UserId")""",
            ];
        }
        else if (db.Database.IsSqlite())
        {
            statements =
            [
                """
                CREATE TABLE IF NOT EXISTS "DeviceTokens" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_DeviceTokens" PRIMARY KEY AUTOINCREMENT,
                    "UserId" TEXT NOT NULL,
                    "Token" TEXT NOT NULL,
                    "Platform" TEXT NOT NULL,
                    "CreatedAt" TEXT NOT NULL,
                    "LastSeen" TEXT NOT NULL
                )
                """,
                """CREATE UNIQUE INDEX IF NOT EXISTS "IX_DeviceTokens_Token" ON "DeviceTokens" ("Token")""",
                """CREATE INDEX IF NOT EXISTS "IX_DeviceTokens_UserId" ON "DeviceTokens" ("UserId")""",
            ];
        }
        else return;

        foreach (var sql in statements) await db.Database.ExecuteSqlRawAsync(sql);
    }
}
